name: Terraform Deployment

on:
  push:
    branches:
      - main           
  workflow_dispatch:   

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
            enable-AzPSSession: false
    environment: azurecloud
    allow-no-subscriptions: false
    audience: api://AzureADTokenExchange
    auth-type: SERVICE_PRINCIPAL
    #      client-id: ${{ secrets.ARM_CLIENT_ID }}
     #     tenant-id: ${{ secrets.ARM_TENANT_ID }}
      #    subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
       #   client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -backend-config="storage_account_name=venusstorageaccount" -backend-config="container_name=venusstatefile" -backend-config="key=venus.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
